# Generated by Django 6.0.3 on 2026-04-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='name',
        ),
        migrations.AddField(
            model_name='university',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='accredationstatus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='affiliationdetails',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='collegecode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='university',
            name='fulladdress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='university',
            name='principle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='requireddocs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='university',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='uhoi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='universityestablishment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='universityname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='university',
            name='universitytype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
