# Generated by Django 6.0.3 on 2026-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0002_remove_university_name_university_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
