# Generated by Django 6.0.3 on 2026-04-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='written_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
