# Generated by Django 6.0.3 on 2026-04-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1', '0005_alter_report_written_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
